name: 'FeishuRBT'

services:
  lark-dify-bot:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - VERIFICATION_TOKEN=${VERIFICATION_TOKEN}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - BOT_NAME=${BOT_NAME}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped